remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "https://ej-shafran.github.io/ui-ts/"
  "API Reference":
    - "https://ej-shafran.github.io/ui-ts/docs/modules"
  "GitHub":
    - "https://github.com/ej-shafran/ui-ts/blob/main/packages/ui-ts/README.md"
